[programs.localnet]
protocol_product = "2cTEcEM1B5pkVFrqSFnUDowgbRvqc5uoagRBAQ1Uehh7"

[programs.devnet]
protocol_product = "2cTEcEM1B5pkVFrqSFnUDowgbRvqc5uoagRBAQ1Uehh7"

[features]
seeds = false
skip-lint = false

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn runJestTests"
